### ISSUE TITLE
editing problem

### ISSUE THREAD

**Issue by rustyblue100** [kolhoffmmm/acf_tags#1]
Hi cool plugin, much needed I would say, there's just an issue when you want to edit your post, when your form is in the front end the field doesn't display the tags already posted, and in the backend the field appears grey and you cannot enter value in it.

**Comment by kolhoffmmm** [comment]
Hi the back end is supposed to be greyed out as in the back end you can
make use of the default tag metabox. On my end I have no problems when I
edit an existing post, the tags show up in the field and I can edit the ,
separated tags or add more.

I use the latest pro version of AFC. I haven't developed it for version 4.

Attached I have the zipped plugin directly from my test site.

Regards

Mouring

On Tue, Mar 3, 2015 at 7:20 PM, rustyblue100 notifications@github.com
wrote:

> Hi cool plugin, much needed I would say, there's just an issue when you
> want to edit your post, when your form is in the front end the field
> doesn't display the tags already posted, and in the backend the field
> appears grey and you cannot enter value in it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kolhoffmmm/acf_tags/issues/1.

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801

**Comment by kolhoffmmm** [comment]
Hi before I forget,

The plugin is only meant for the frontend & the field will always show
empty in the backend as it is saving the values to the tags taxonomy or
your custom tags taxonomy. If you look in the backend you should be able to
see that tags are allocated to the post

Mouring

On Tue, Mar 3, 2015 at 7:20 PM, rustyblue100 notifications@github.com
wrote:

> Hi cool plugin, much needed I would say, there's just an issue when you
> want to edit your post, when your form is in the front end the field
> doesn't display the tags already posted, and in the backend the field
> appears grey and you cannot enter value in it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kolhoffmmm/acf_tags/issues/1.

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801

**Comment by rustyblue100** [comment]
Hi, and thank you for the quick response, I'm using the latest ACF pro as well, everything is working fine except of the already post tags that doesn't shows up in the front end, must be something on my side that is conflicting, I'll investigate a little more...

**Comment by kolhoffmmm** [comment]
No problem, make sure you select a non hierarchical taxonomy like tags and
that postype & taxonomy are linked. It works with custom postypes & custom
tag lime taxonomies.

Will probably answer any more questions only tomorrow as it is night time
here in South Africa

Regards

Mouring

**Comment by rustyblue100** [comment]
Thank you, have a nice sleep from Canada!

**Comment by kolhoffmmm** [comment]
Hi i found the problem. The problem only happened when you had 1 tag. I
always tested with more then 1 tag.

I was testing for  terms > 1 when I was loading the terms to populate the
field

I fixed the function now

On Tue, Mar 3, 2015 at 9:02 PM, rustyblue100 notifications@github.com
wrote:

> Thank you, have a nice sleep from Canada!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kolhoffmmm/acf_tags/issues/1#issuecomment-77010938.

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801

**Comment by kolhoffmmm** [comment]
Hi please re download/install and let me know if it solved the issue.

Thanks

On Wed, Mar 4, 2015 at 11:16 AM, Mouring Kolhoff kolhoffmmm@gmail.com
wrote:

> Hi i found the problem. The problem only happened when you had 1 tag. I
> always tested with more then 1 tag.
> 
> I was testing for  terms > 1 when I was loading the terms to populate the
> field
> 
> I fixed the function now
> 
> On Tue, Mar 3, 2015 at 9:02 PM, rustyblue100 notifications@github.com
> wrote:
> 
> > Thank you, have a nice sleep from Canada!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/kolhoffmmm/acf_tags/issues/1#issuecomment-77010938.
> 
> ## 
> 
> Mouring Kolhoff
> http://www.smesolutions.co.za
> Cell     +27-84-5053594
> Office  +27-12-6673245
> Fax     086 663 8801

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801

**Comment by kolhoffmmm** [comment]
Hi,

I updated the plugin again, with the last fix I introduced another bug.
This is fixed now. Version 1.0.2 & the master should be correct now.

On Wed, Mar 4, 2015 at 11:35 AM, Mouring Kolhoff kolhoffmmm@gmail.com
wrote:

> Hi please re download/install and let me know if it solved the issue.
> 
> Thanks
> 
> On Wed, Mar 4, 2015 at 11:16 AM, Mouring Kolhoff kolhoffmmm@gmail.com
> wrote:
> 
> > Hi i found the problem. The problem only happened when you had 1 tag. I
> > always tested with more then 1 tag.
> > 
> > I was testing for  terms > 1 when I was loading the terms to populate the
> > field
> > 
> > I fixed the function now
> > 
> > On Tue, Mar 3, 2015 at 9:02 PM, rustyblue100 notifications@github.com
> > wrote:
> > 
> > > Thank you, have a nice sleep from Canada!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/kolhoffmmm/acf_tags/issues/1#issuecomment-77010938.
> > 
> > ## 
> > 
> > Mouring Kolhoff
> > http://www.smesolutions.co.za
> > Cell     +27-84-5053594
> > Office  +27-12-6673245
> > Fax     086 663 8801
> 
> ## 
> 
> Mouring Kolhoff
> http://www.smesolutions.co.za
> Cell     +27-84-5053594
> Office  +27-12-6673245
> Fax     086 663 8801

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801

**Comment by rustyblue100** [comment]
Perfect! Everything is working now, I was always checking with one tag on my side...Thank you very much!

**Comment by kolhoffmmm** [comment]
Great I will close the issue now, but if you find another issue just let me
know.

Regards

On Wed, Mar 4, 2015 at 2:24 PM, rustyblue100 notifications@github.com
wrote:

> Perfect! Everything is working now, I was always checking with one tag on
> my side...Thank you very much!
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/kolhoffmmm/acf_tags/issues/1#issuecomment-77148768.

## 

Mouring Kolhoff
http://www.smesolutions.co.za
Cell     +27-84-5053594
Office  +27-12-6673245
Fax     086 663 8801
